<a href="https://colab.research.google.com/github/myname-baskaran/AI-JOURNEY/blob/main/Day12_Pandas_Summary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Day 12 - Pandas: Summary Functions and Maps

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Ticker": ["DBS", "OCBC", "UOB", "SIA", "Grab", "SeaLtd"],
    "Price":  [35.20, 14.80, 31.50, 6.40, 4.10, 78.30],
    "Sector": ["Banking", "Banking", "Banking", "Airline", "Tech", "Tech"]
})

In [3]:
df.Price.describe()

count     6.000000
mean     28.383333
std      27.587346
min       4.100000
25%       8.500000
50%      23.150000
75%      34.275000
max      78.300000
Name: Price, dtype: float64

In [6]:
print(df.Price.mean())

28.383333333333336

In [8]:
print(df.Ticker.unique())

['DBS' 'OCBC' 'UOB' 'SIA' 'Grab' 'SeaLtd']

In [10]:
print(df.Ticker.value_counts())

Ticker
DBS       1
OCBC      1
UOB       1
SIA       1
Grab      1
SeaLtd    1
Name: count, dtype: int64

In [14]:
df['price_usd'] = df.Price.map(lambda p: round(p * 0.74,2))

In [15]:
df["Price"].describe()

count     6.000000
mean     28.383333
std      27.587346
min       4.100000
25%       8.500000
50%      23.150000
75%      34.275000
max      78.300000
Name: Price, dtype: float64

In [16]:
df.Sector.value_counts()

Sector
Banking    3
Tech       2
Airline    1
Name: count, dtype: int64

In [18]:
df['Price_rounded'] = df.Price.map(lambda p: round(p))